; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:fcplc]
platform = espressif32@6.9.0
board = 4d_systems_esp32s3_gen4_r8n16
framework = arduino
monitor_speed = 115200
board_build.partitions = partitions/custom_16MB_ota.csv
board_build.filesystem = littlefs
build_unflags = -std=gnu++11 -std=c++11
build_flags = 
	-std=gnu++17
	-Wno-deprecated-declarations
	-mtext-section-literals
	-DLOGGER_USE_COLOR=0
	-DBOARD_FCPLC_3V1
	-DFW_VERSION=\"1.0.0\"
lib_deps = 
	bblanchon/ArduinoJson@7.4.2
	gyverlibs/FastBot2@1.2.5
	me-no-dev/ESPAsyncWebServer
	links2004/WebSockets@2.4.2
